### ISSUE TITLE
Enabling Fossdash overrides existing CRON Setting

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#10]
With following scenario:
1. Enable Fossdash
1. Modify default CRON settings
1. Update settings -> new config OK
1. Disable Fossdash and update config -> CRON is removed -> OK
1. Enable Fossdash  and update config
    - Now the cron is set back to default `* * * * *`
    - although the custom value is still stored in the database

**Comment by darshank15** [comment]
Fixed

Link to commit : https://github.com/Orange-OpenSource/fossology/pull/3/commits/3e9bd88f36d990f70d5ce27c197fc5f3a7bf4f4c

**Comment by NicolasToussaint** [comment]
Works, closing
