### ISSUE TITLE
Change metrics data filename to include timestamp

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#11]
It would be very handy to include a timestamp in the filenames rather than a random value.

- now: `/srv/fossology/repository/fossdash/fossdash-publish.py.GC3ZIR`
- preferred:, something like this, for ex.
   -  `/srv/fossology/repository/fossdash/fossdash-publish.20200708_114422`

**Comment by darshank15** [comment]
Hopefully, formate is fossdash-publish.YYYYMMDD_HHMMSS

**Comment by darshank15** [comment]
Done with the above formate.

Link to commit :https://github.com/Orange-OpenSource/fossology/pull/3/commits/e45e32bf7d74eb8014426a50ebc3c2dc0142c5e0

**Comment by NicolasToussaint** [comment]
Example of new filename: `fossdash-publish.20200820_100401`, perfect
