### ISSUE TITLE
Restrict InfluxDB posts

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#12]
**For InfluxDB:**

* disable Influx Admin account (already the case in docker-compose)
   * [note] USER account seems to be necessary for Grafana to query the data (to be confirmed)
* add authentication for to be allowed to post data (see [InfluxDB Authentication](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization))
  * Ideally, have an authentication token for a given instance ID...

**Comment by darshank15** [comment]
Done.
part1: Enable authentication in InfluxDB. ==> Commit :  https://github.com/Orange-OpenSource/fossology/pull/3/commits/3b28e4a0486a9a730b890849c4c19fb689b1d64a
part2: In the publisher script, Added authentication head to authenticate the sending data request. ==> Commit : https://github.com/Orange-OpenSource/fossdash/pull/1/commits/beff4fcc6e1ef51afc03805b393db2a1d54e4c05

**Comment by darshank15** [comment]
Currently, I have done authentication using a username and password for the database as discussed with @bartos 

I have tried with token-based authentication But don't sure how we can generate a token for our specific database of InfluxDB.
https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization#authenticate-using-jwt-tokens

**Comment by darshank15** [comment]
Yes, We can do now token-based authentication as well, 

But we Compulsory required expiration time ( UnixTimestamp formate ).
```
header = {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvc3N5IiwiZXhwIjoxNjI2NzcwODg4fQ.cXhH7VhMxv2kFsE69aXVH-7PGO8cowuvTW5Fow9dXn4'}
fossdash_response = requests.post(fossdash_url, headers=header,data=file_data)
```

**Comment by darshank15** [comment]
Done the InfluxDB authentication using token-based.
https://github.com/Orange-OpenSource/fossology/pull/3/commits/0f81a157edcab002c99f5e0206fd8d4496ed8784

**Comment by darshank15** [comment]
Comes up with both types of authentication based on the dropdown selection.

0. Token-based authentication.
1. Username_password authentication.

As a discussion, we can't have performs an administration related operation to influxDB.

As Fossology, We need to asks username and password assigned to us OR token assigned to us for pushing data to influxDB.
We need to update these data though sysconfig UI page. Whenever the token gets expired.

**Comment by NicolasToussaint** [comment]
Works as expected

Wrong password leads to authentication error, as expected:
```
2020-08-20 10:19:02.085207
Fossology Instance UUID =  fossology-dev-2
All data metrics Generated
publishing FossDash URL = http://influxdb:8086/write?db=fossology_db
sending file to influxDB = /srv/fossology/repository/fossdash/fossdash-publish.20200820_101902
user_pass authentication 
status code = 401
{"error":"authorization failed"}

sending file to influxDB = /srv/fossology/repository/fossdash/fossdash-publish.20200820_101902
user_pass authentication 
status code = 401
{"error":"authorization failed"}

find_cmd =  find /srv/fossology/repository/fossdash -maxdepth 1 -iname "fossdash-publish*.reported" -ctime +4 > /srv/fossology/repository/fossdash/fossdash_clean_file_list
```

Concerning the use of token, it works well, but the process to create a token is not easy to find...
