### ISSUE TITLE
Grafana: Explore and preinstall "panel  plugins"

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#13]
Grafana proposes extra plugins.

Specifically: *[Panel plugins](https://grafana.com/grafana/plugins?direction=asc&orderBy=weight&utm_source=grafana_plugin_list&type=panel) allow new data vizualizations to be added to Grafana, for both time series and non-time series data.*

Short list to install and try:
- https://grafana.com/grafana/plugins/grafana-piechart-panel
- https://grafana.com/grafana/plugins/mtanda-histogram-panel
- https://grafana.com/grafana/plugins/michaeldmoore-multistat-panel
- https://grafana.com/grafana/plugins/mxswat-separator-panel
- https://grafana.com/grafana/plugins/vonage-status-panel

They seem easy to install, but a docker volume will be required to restart the service and keep the plugin installed

**Comment by darshank15** [comment]
I and Bartl tried using grafana plugin provisioning But didn't work out.

Done, Using Environment variable in the docker-compose file.

` - "GF_INSTALL_PLUGINS=grafana-piechart-panel,vonage-status-panel,mxswat-separator-panel,mtanda-histogram-panel,michaeldmoore-multistat-panel"`

**Comment by NicolasToussaint** [comment]
Work well

Here is the list of visualization plugins available by default:
![image](https://user-images.githubusercontent.com/22956329/90770092-926f8800-e2f1-11ea-9a19-bb708a86c099.png)
