### ISSUE TITLE
Create generic Instance-oriented dashboard

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#14]
Grafana has a great feature called Variables: https://grafana.com/docs/grafana/latest/reference/templating/

> A variable is presented as a dropdown select box at the top of the dashboard. It has a current value and a set of options. The options is the set of values you can choose from.

This can allow us to provide instances-specific dashboards, letting the user select to instance for which they want to see the graphs.

The variables can be populated from the datababse, using simple [queries](https://grafana.com/docs/grafana/latest/reference/templating/#query-options): we could build a drop-down variable list based of on query, refreshed regularly.

So if an instance sends its name as a metric, we can build a dashboard for 1 instance, and let the user select which instance s-he wants to apply

**Comment by darshank15** [comment]
Done
* Added an INSTANCE type in every metric field. So that we can perform filtering based on Instance ID.
  * Commit: https://github.com/Orange-OpenSource/fossology/pull/3/commits/4519e84646768a1a61e221a922657064778e15e0
* Created Instance specific Dashboard. 
   * Commit: https://github.com/Orange-OpenSource/fossdash/pull/1/commits/7aca878b4c0a1c32a43ac4b9223d64d5a22ade04

**Comment by NicolasToussaint** [comment]
The two dashboards are automatically created, it is easy to switch between them, great !

Maybe the the data at the top of the page, with versioning related values, should not be included in the generic dashboard.
Unless if all instances have the same, or provide a clear rule to select which instance data to choose - maybe the most recent ? But that might be hard to achieve with InfluxDB queries.

![image](https://user-images.githubusercontent.com/22956329/90268313-1e4b6500-de57-11ea-8873-619bc4d0f266.png)
![image](https://user-images.githubusercontent.com/22956329/90268324-23a8af80-de57-11ea-9d51-422dc240d5a4.png)

**Comment by darshank15** [comment]
Done.

Related PR : https://github.com/Orange-OpenSource/fossdash/pull/3

**Comment by NicolasToussaint** [comment]
works perfectly, closing
