### ISSUE TITLE
Sysconfig UI page upgrade to bootstrap and some CSS.

### ISSUE THREAD

**Issue by darshank15** [darshank15/GSoC_2020_FOSSOlogy#19]
* Added Bootstrap to Sysconfig Page
* Align the first column of all the table to occupy the same space.

**Comment by darshank15** [comment]
Any More UI suggestions are most welcome, As I am not a UI expert. 
For Now, Linkt to commit : https://github.com/Orange-OpenSource/fossology/pull/3/commits/1fbe571d778da4930f0305470102b36f01abdfb9

**Comment by darshank15** [comment]
![Screenshot from 2020-07-17 01-09-15](https://user-images.githubusercontent.com/18461170/87715036-587b0580-c7ca-11ea-9bff-2a709fee9a4d.png)

**Comment by NicolasToussaint** [comment]
Looks very good to me - though I'm certainly not a UI expoert either ;-)
