### ISSUE TITLE
Dashboard Configuration 

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#2]
The point of this issue is to add the possibility to configure various elements around the Fossology dashboard.

# Cron execution

The [Python script](https://github.com/Orange-OpenSource/fossology/blob/dev/fossdash-exporter/install/fossdash/fossdash-publish.py) that pushes metrics is triggered with cron.

For the moment, that Cron configuration is hardcoded, or cumbersome to configure
- the[ frequency is hard coded](https://github.com/Orange-OpenSource/fossology/blob/3434cbf82da7124a4fbf17a5573d77493d0d5967/install/db/db.cron#L14) in the source code
- the path to the [DB.conf](https://github.com/Orange-OpenSource/fossology/blob/dev/fossdash-exporter/install/defconf/Db.conf.in) file is forced to the [Docker specific path](https://github.com/Orange-OpenSource/fossology/blob/3434cbf82da7124a4fbf17a5573d77493d0d5967/install/fossdash/fossdash-publish.py#L31), but it is different when installed from source

# Grafana URL

1. The remote Grafana database URL is [configured in the docker-compose](https://github.com/Orange-OpenSource/fossology/blob/3434cbf82da7124a4fbf17a5573d77493d0d5967/docker-compose.yml#L36) file
1. It is then written to a conf file, from Envronment variable, in the [docker-entrypoint](https://github.com/Orange-OpenSource/fossology/blob/3434cbf82da7124a4fbf17a5573d77493d0d5967/docker-entrypoint.sh#L31) script
1. and then read from the file[ in the script](https://github.com/Orange-OpenSource/fossology/blob/3434cbf82da7124a4fbf17a5573d77493d0d5967/install/fossdash/fossdash-publish.run#L26) (because env variable are not passed to the Cron script)

# How to configure

In the branch, there is already a *customize* entry to configure the Fossdash URL, that is not used.

![image](https://user-images.githubusercontent.com/22956329/83899009-05884a00-a758-11ea-8a6a-4dadb1d2b6fd.png)

The need is to be able to:
- easily change the Fossdash URL / Cron frequency from the web interface
- store the values to the database
- read the data directly from the shell / Python scripts
- make sure the solution works when Fossology is deployed both from Docker and from Sources (because installation paths differ)

**Comment by NicolasToussaint** [comment]
As discussed, it is now expected to enter the full URL to InfluxDB, including the database name.
The change in the UI is correctly taken into account for following pushes.

Could we add a hint to a proper configuration to the user ?
For ex. indicate a possible conf for source code and Docker setup:
- Source Code: `http://localhost:8086/write?db=fossology_db`
- Docker setup: `http://influxdb:8086/write?db=fossology_db`

**Comment by darshank15** [comment]
Done

**Comment by NicolasToussaint** [comment]
URL configuration works well, closing
