### ISSUE TITLE
Having drop down for Two different kind of authentication on InfluxDB, Show/Hide below Auth fields accordingly

### ISSUE THREAD

**Issue by darshank15** [darshank15/GSoC_2020_FOSSOlogy#20]
We want to have a drop-down to select the type of authentication for an influxDb.

Based on selection it should able to gets next authentication input box.
If chosen Authtype = Token based, Something similar to below [ PS: We need to hide username and password field ]
![Screenshot from 2020-07-25 16-06-23](https://user-images.githubusercontent.com/18461170/88455186-fa68b500-ce90-11ea-90b6-3dc904d863b4.png)

If chosen AuthType = Username_pass, Something similar to below. [ PS: We need to hide token field]
![Screenshot from 2020-07-25 16-06-13](https://user-images.githubusercontent.com/18461170/88455194-05bbe080-ce91-11ea-9804-98e7524e8428.png)

**Comment by darshank15** [comment]
Done !!!
Link to commit: https://github.com/fossology/fossology/pull/1769/commits/ef2fa7002cfa9a891176a0a13722afe75082c2b3

**Comment by NicolasToussaint** [comment]
Works well, closing
