### ISSUE TITLE
Configuration and behaviour of "Fossdash reported files cleaning"

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#21]
Related to #7 (that contains multiple tasks)

The conf entry could be made more expicit:
  - reformulate `Fossdash reported files cleaning` to `number of days for which the successfully pushed metrics are archived. Older data will be deleted. Leave empty to disable cleanup`
- Accept 0 to keep no data
- Beware of rounding mechanism with `-ctime` option: `+1` means: modified at least 2 days ago
So, if `N` is the configured value, use: `find -ctime +(N-1)`
- for N=1:  `find -ctime +0` will list files changed more than 1 day ago.

**Comment by darshank15** [comment]
Got everything

Bt Accept 0 to keep no data ==> Meaning when user enter 0 == It is going to be N-1 ==> -1 Then what to do?

Or When field value 0, then Delete every reported files?

**Comment by NicolasToussaint** [comment]
Yes, if you have 0, then I would not save the archive file at all, and remove all existing ones (directly, without using `find`)

**Comment by NicolasToussaint** [comment]
Works well, closing
