### ISSUE TITLE
Log file grows forever

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#26]
The Fossdash log file `/srv/fossology/repository/fossdash/fossdash.log` gets pretty large after a while.

We could move it to `/var/log/fossology/fossdash.log`, with log rotation enabled, like for the base fossology log

**Comment by darshank15** [comment]
Done:: https://github.com/fossology/fossology/pull/1769/commits/5edf7f1a6b4344332bb56f53a770277cb7c92a95.

log rotation is enabled by fossology for all `.log` files inside the folder `/var/log/fossology`. So no need to configure anything for it.
https://github.com/fossology/fossology/blob/master/debian/fossology-scheduler.logrotate

**Comment by NicolasToussaint** [comment]
Log file moved to `/var/log/fossology/` + log rotate already configured, closing
