### ISSUE TITLE
Merging multiple fossdash script into single fossdash script 

### ISSUE THREAD

**Issue by darshank15** [darshank15/GSoC_2020_FOSSOlogy#5]
Currently, we have two scripts are fossdash-publish.py (Python script)  and fossdash-publish.run (bash script), also fossdash.conf file.

Task1: We can merge these two scripts into a single script, Which can easy to maintain and execute for fossdash.

Now, there is no need for a fossdash.conf file as we are storing fossdash URL into the database, We can directly fetch latest fossdash URL from the database only.

Task2: segregate the VERSION content into three different parts: version, total commit since the last release, latest commit ID.

**Comment by NicolasToussaint** [comment]
All is working well, and merged,

Closing, Bravo :-)
