### ISSUE TITLE
Rename UUID on a Fossology instance

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#6]
The automatic creation and storage of a UUID per instance on first run is very good since it makes it possible to have a dashboard that works out of the box without tuning, without risk of collision when multiple Fossology instances are used.

However, they are hard to read, and meaningless. The possibility to specifically name a Fossology instance and use that name instead of the automatically generated UUID would be very useful.

This would include:
- add a configuration option in the UI to set a specific name
   - -> if left blank, using automatically generated UUID
- The name should be stored in the database
   - maybe the UUID history should also be stored ?
- When changing the UUID, we should trigger a query in InfluxDB database so as to change the old UUID to the new one.
   - This does not have to be done immediately, but could executed at next metric push (triggered by Cron)
   - care should be taken to re-try the UUID change request in the InfluxDB database if it were to fail.
- all following metrics generation should be done with the new UUID

Two ideas out of my head to store the action
-  create a file `fossdash.actions` containing the necessary info (action type, old name, new name), so that it can be 
retried every time new metrics are to be pushed
- add a flag in the database to store the need to trigger a UUID rename. This would require storing the UUID history

**Comment by darshank15** [comment]
Currently we are not able to do UPDATE on influx DB. I have done with maintaining history of Instance UUID, But when it comes to updating old InfluxDB data, I found this influxdb Issue : https://github.com/influxdata/influxdb/issues/3904.
So what we can do is after updated instance UUID, all following metrics generation should be done with the new UUID. Maybe we can not able to UPDATE the old influx data.

**Comment by NicolasToussaint** [comment]
Oh I see :-(
Let's give up the update from old to new name in the database for now.
We can always work on it later, maybe by looping over all old values and inserting them again with the new UUID.

**Comment by NicolasToussaint** [comment]
The new UUID configured in the UI a correctly taken into account for new metrics that have been pushed.

Since updating metrics that were created with previous UUIDs is far from straight forward, let's close this issue for now, and postpone that specific need for the future.

**Comment by darshank15** [comment]
As of now, We are done with updating old reported files and replace old instance UUID with new instance ID and push again all these files to influxDB.
