### ISSUE TITLE
Cleaning task of old fossdash reported  files and Cron Job configuration

### ISSUE THREAD

**Issue by darshank15** [darshank15/GSoC_2020_FOSSOlogy#7]
**Task-1  Cleaning old fossdash reported files.**
As of now we generating all reported files posts send the data to the influxDB. As the fossdash script may be running every day, the Amount of all reported files in local space will be larger and more disk consumption over the period of time.
Can We have the functionality to delete let's say X day or older all reported file to save disk space?

**Task-2 Cron job configuration to schedule an interval for the fossdash script file.**
From configuration, the user can change the corn job schedule interval for fossdash.

**Task-3 Have Enable/Disable button to control the functionality of the fossdash.**
Have Button to start and stop the functionality of fossdash.

**Comment by darshank15** [comment]
Done

**Comment by NicolasToussaint** [comment]
All Good !
