### ISSUE TITLE
Some CRON setting ignored

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#9]
When setting a CRON with a `/` command, the new setting is ignored:
![image](https://user-images.githubusercontent.com/22956329/86771285-3eb32300-c052-11ea-8720-5c5cefde9074.png)

**Comment by darshank15** [comment]
Done !!!
https://github.com/fossology/fossology/pull/1769/commits/2b79d1ef152a3f8b69c4e178e2464fbb284d1d58

**Comment by NicolasToussaint** [comment]
This works fine, closing
